// SCRIPTED PIPELINE 

//node {
//	stage('Build') {
//		echo "Build"
//	}
//	stage('Test') {
//		echo "Test"
//	}
//	stage('Integration Test') {
//		echo "Integration Test"
//	}
//}

// DECLARATIVE PIPELINE
pipeline {
//	agent { docker { image 'node:latest' } }
//	agent { docker { image 'maven:3.6.3' } }
	agent any

	environment{
		DockerHome = tool 'my-docker'
		MavenHome = tool 'my-maven'
		PATH = "$DockerHome/Bin:$MavenHome/Bin:$PATH"
	}
	stages {
		stage ('Build'){
			steps {
				sh 'docker --version'
				sh 'maven --version'
				echo "Build"
				echo "PATH - $PATH"
				echo "BUILD_NUMBER - $env.BUILD_NUMBER"
				echo "BUILD_ID - $env.BUILD_ID"
				echo "BUILD_URL - $env.BUILD_URL"
				echo "BUILD_TAG - $env.BUILD_TAG"
				echo "JOB_NAME - $env.JOB_NAME"
			}
		} 
		stage ('Test'){
			steps {
				echo "Test"
			}
		}
		stage ('Integration Test'){
			steps {
				echo "Integration Test"
			}
		}
	}
	post {
		always {
			echo "This message shows you in every run."
		}
		success {
			echo "All steps have finished successfuly."
		}
		failure {
			echo "There is something wrong."
		}
	}
}